spring.application.name=webapp
spring.datasource.url=jdbc:postgresql://localhost:5432/pdfapp
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.auto-commit=false
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
logging.level.org.springframework.web=DEBUG
openai.api.key=sk-proj-XXXXXXXXXXXXXXXXXXXXXXXXXXXXX

app.storage.path=uploads